export const SHEET_IDS = {
  basicInfo: "1bSyTcF_2SXvH5u3TMxmqZGxtCDa-6c-Cd4RP3Icgc1k",
  qualifications: "1BmnXoX0KA_1fCC_4BxEY9xxYXwB-jCGfa_9EJfvW2BE",
  teaching: "1C9p4NBoG0drsZsh32Etz5V4V2cmWmZX1mJlxAEo0wms",
  courses: "17rQUpzLb7kjvSOOxmgz9cU-bFEJz6dwkjWaowsi-SzU",
  institutional: "1vK1gMYP5hP6fU0RbccglnS030IOtfDoIaT5vXEghBHE",
  journalPublications: "1CnjsR2TkCcYndkw27tWFLD5Yy5Ma2vky4sMYnbHqDJI",
  conferencePublications: "1z9_eV9zPLqjR-wGMbE5b_9f6o-tYResFfeBMo4xoxn0",
  researchProjects: "1_W8QksqRbXcyvzDPBp99aBuVBlJbJ_Sw97Ypx4XPp4Q",
  patents: "1O-J9RU-VjU3JsbZp2W5JY-oEM5ku5OnWULk4y7mwd_Q",
  fdp: "1oArlDg9v_vK9-UDCk9vD8exZAMZB0NCaFRvhBLxJnOA",
  memberships: "1gBO7uMh8fOp--sWwldeMs2KMDZqtK5pCPZ66EIL-e88",
  responsibilities: "1QnwrVdqLTz1z_qC4dNwAUbHo8qcaHl1KGH8yDmiuzNM",
  mentoring: "1V9ufMdVgGs4plrUjFNhIo8b-v4s3rs_LOBtu3THivgg",
  declaration: "1z1rQlDBrx0mglcz3zyZFUlRDeaKeQEvxb01kz2YuThw",
  awards: "1AGbqO4UhyIFEASjP79o_1lGr67rhsjdvjB7Et_GEjuk",
  extension: "1UIcDm6Yvu8B8nmeNsg5jwuTW_r2hehtwq_H3QjjudNw",
  skills: "1mvn_Z8ocFyAHN7cK3BSIwuk_6DIt9OckY5mRVlllziI",
  onlineProfiles: "1QIIOW5kKPNLgkalx4sO3Nk5wVjE0jU_Wtk4y-IB0CXA",
  contactMe: "1aTRFtmEm7HcAcUyCnhAXCX1gBvBlLTpYjZJgo-Ii_co",
};

export const SECTION_TITLES: Record<keyof typeof SHEET_IDS, string> = {
  basicInfo: "Basic Information",
  qualifications: "Academic Qualifications",
  teaching: "Teaching Experience",
  courses: "Courses Taught",
  institutional: "Institutional Contributions",
  journalPublications: "Journal Publications",
  conferencePublications: "Conference Publications",
  researchProjects: "Research Projects",
  patents: "Patents & Innovations",
  fdp: "FDP & Certifications",
  memberships: "Professional Memberships",
  responsibilities: "Academic Responsibilities",
  mentoring: "Student Mentoring",
  declaration: "Declaration",
  awards: "Awards & Recognitions",
  extension: "Extension & Outreach",
  skills: "Technical Skills",
  onlineProfiles: "Connect",
  contactMe: "Contact Me",
};

export const CONTACT_FORM_URL = ""; // PASTE YOUR GOOGLE WEB APP URL HERE
